services:
  pandoc:
    image: pandoc/latex:3.6.3-alpine
    restart: always
    hostname: pandoc_convert
    container_name: pandoc_convert
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
    user: "${UID}:${GID}"
    volumes:
      - ${PROJECT_PATH}:/data:rw